ecommerce/business/urls.py
from django.urls import path
from . import views

from .views import *
app_name = 'business'
urlpatterns = [
    
    path("", views.dashboard, name="home"), 
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser , name="logout" ),
    path('add_product/', views.add_product, name= 'add-product'),
    path('add_service/', views.add_service, name= 'add-service'),    
    path('profile/', views.profile, name= 'profile'),
    path('update_info/', views.update_info, name= 'update-info'),
    path('update_profile/', views.update_profile, name= 'update-profile'),
    path('update_password/', views.update_password, name= 'update-password'),
    path('product/<int:pk>', views.product, name= 'product'),
    path('service/<int:pk>', views.service, name= 'service'),
    path('category/<str:foo>', views.category, name= 'category'),
    path('search/', views.search, name= 'search'),
    path('about/',views.about,name='about'),
    path("contact/",views.contact,name="contact"),
    path('customer/', views.customer,name='customer'),    
    path("services/", ServiceListView.as_view(), name="service-list"),    
    path("products/", ProductListView.as_view(), name="product-list"),
    path('registerBusiness/',CreateBusinessUser.as_view(), name='register_business'),
    path('registerCustomer/',CreateCustomerUser.as_view(), name='register_customer'),    
    path("manage/",views.ManageBusiness, name ='manage'),
    path("order/",views.order,name='order'),
    path("create/",views.order_create,name='order_create'),
    path('business/<int:Business_id>/', views.BusinessPage, name='business_Page'),
    path("check/<int:pk>/", views.check, name="check"),
    path("approve/<int:pk>/", views.approve, name="approve"),
    path("updatePdt/<int:pdt_id>/", views.UpdateProduct, name="UpdateProduct"),
    path("updateService/<int:service_id>/", views.UpdateService, name="UpdateService"),
    path("appointment/<int:service_id>/<int:business_id>", views.appointment, name="book"),
    
]

ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:business_id>/<int:product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name = 'cart_remove'),
]   

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("business.urls", namespace='business')),
    path('cart/',include("cart.urls", namespace='cart')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models

# Create your models here.

ecommerce/cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices = PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(required = False,
                                  initial=False,
                                  widget=forms.HiddenInput)
    

ecommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from business.models import Product, Business
from .cart import Cart
from .forms import CartAddProductForm
from business.models import *
from business.forms import *

@require_POST
def cart_add(request, product_id, business_id):
    cart = Cart(request)    
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
                 product_id = product_id, 
                 business_id = business_id,
                 quantity = cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override':True
        })
    return render (request, 'cart/detail.html', {'cart':cart})

ecommerce/cart/templates/cart/detail.html
{% extends "base.html"%}
{% load static %}

{% block title %}
    Your Shopping Cart
{% endblock %}

{% block content %}
<div class="container px-3 my-5 clearfix">
    <div class="card">
      <div class="card-header bg-light border-light">
        <h2>Shopping Cart</h2>
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            <div class="d-flex justify-content-between align-items-center">
              <p class="mb-0">Your cart: <a href="{% url 'cart:cart_detail' %}">{{ total_items }} item{{ total_items|pluralize }}</a> | Shs {{ cart.get_total_price }}</p>
            </div>
          {% else %}
            <p class="text-center mb-0">Your cart is empty</p>
          {% endif %}
        {% endwith %}
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover m-0">
            <thead>
              <tr>
                <th class="text-center py-3 px-4" style="min-width: 300px;">Product Name &amp; Details</th>
                <th class="text-right py-3 px-4" style="width: 150px;">Price</th>
                <th class="text-center py-3 px-4" style="width: 200px;">Quantity</th>
                <th class="text-right py-3 px-4" style="width: 200px;">Total</th>
                <th class="text-center align-middle py-3 px-0" style="width: 50px;"></th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart %}
                {% with product=item.product %}
                  <tr>
                    <td class="p-4 d-flex align-items-center">
                        <img src="{{ product.photo.url }}" alt="{{ product.name }}" class="d-block ui-w-40 ui-bordered me-4" alt="">
                        <div >
                          <a href="{% url 'business:product' product.id %}" class="d-block text-dark">{{ product.name }}</a>
                        </div>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">SHS {%if product.discount %} {{product.discounted_price}} {% else %}{{ product.price }} {% endif %}</td>
                    <td class="align-middle p-4">
                      <form action="{% url 'cart:cart_add' business_id=product.Business.id product_id=product.id %}" method="post">
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.override }}
                        <input type="submit" value="Update" class="btn btn-sm btn-primary">
                        {% csrf_token %}
                      </form>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">SHS {{ item.total_price }}</td>
                    <td class="text-center align-middle px-0">
                      <form method="post" action="{% url 'cart:cart_remove' product.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link p-0"><i class="fas fa-trash-alt text-danger"></i></button>
                      </form>
                    </td>
                  </tr>
                {% endwith %}
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer bg-light border-light">
        <div class="d-flex justify-content-between align-items-center">
          <div class="text-muted">Total price</div>
          <div class="text-large font-weight-bold">Shs {{ cart.get_total_price }}</div>
        </div>
        <div class="d-flex justify-content-end mt-3">
          <a href="{% url 'business:product-list' %}" class="btn btn-outline-secondary me-2">Back to shopping</a>
          <a href="{% url 'business:order_create'%}" class="btn btn-primary">Checkout</a>
        </div>
      </div>
    </div>
</div>

{% endblock %} 

    