ecommerce/business/urls.py
from django.urls import path
from . import views

from .views import *
app_name = 'business'
urlpatterns = [
    
    path("", views.dashboard, name="home"), 
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser , name="logout" ),
    path('add_product/', views.add_product, name= 'add-product'),
    path('add_service/', views.add_service, name= 'add-service'),    
    path('profile/', views.profile, name= 'profile'),
    path('update_info/', views.update_info, name= 'update-info'),
    path('update_profile/', views.update_profile, name= 'update-profile'),
    path('update_password/', views.update_password, name= 'update-password'),
    path('product/<int:pk>', views.product, name= 'product'),
    path('service/<int:pk>', views.service, name= 'service'),
    path('category/<str:foo>', views.category, name= 'category'),
    path('search/', views.search, name= 'search'),
    path('about/',views.about,name='about'),
    path("contact/",views.contact,name="contact"),
    path('customer/', views.customer,name='customer'),    
    path("services/", ServiceListView.as_view(), name="service-list"),    
    path("products/", ProductListView.as_view(), name="product-list"),
    path('registerBusiness/',CreateBusinessUser.as_view(), name='register_business'),
    path('registerCustomer/',CreateCustomerUser.as_view(), name='register_customer'),    
    path("manage/",views.ManageBusiness, name ='manage'),
    path("order/",views.order,name='order'),
    path("create/",views.order_create,name='order_create'),
    path('business/<int:Business_id>/', views.BusinessPage, name='business_Page'),
    path("check/<int:pk>/", views.check, name="check"),
    path("approve/<int:pk>/", views.approve, name="approve"),
    path("updatePdt/<int:pdt_id>/", views.UpdateProduct, name="UpdateProduct"),
    path("updateService/<int:service_id>/", views.UpdateService, name="UpdateService"),
    path("appointment/<int:service_id>/<int:business_id>", views.appointment, name="book"),
    
]

ecommerce/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:business_id>/<int:product_id>/', views.cart_add, name = 'cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name = 'cart_remove'),
]   

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("business.urls", namespace='business')),
    path('cart/',include("cart.urls", namespace='cart')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/business/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django.contrib.auth.models import User

from django.forms.widgets import DateTimeInput


from .models import *

class CreateUserForm(UserCreationForm):    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']    

class Business_Form(ModelForm):
    class Meta:
        model = Business
        fields ="__all__"
        exclude=['user']

class Customer_Form(ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"
        exclude=['user']

class UpdateProfileForm(UserChangeForm):
    password= None
    email = forms.EmailField(label="",  widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter E-mail'}))
    first_name = forms.CharField(label="",max_length=150, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter first name'}))
    last_name = forms.CharField(label="",max_length=150, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter last name'}))
       
    class Meta:
        model = User
        fields = ['email','first_name','last_name' ]

class UpdatePasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label="",max_length=150, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Enter new password', }))
    new_password2 = forms.CharField(label="",max_length=150, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Re-enter the password'}))

    class Meta:
        model = User
        fields = ['new_password1', 'new_password2' ]

class UpdateInfoForm(ModelForm):
    first_name = forms.CharField(label="", max_length=50, required=False, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Enter first name'})) 
    last_name = forms.CharField(label="", max_length=50, required=False,  widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Enter last name'})) 
    phone = forms.CharField(label="", max_length=50, required=False, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Enter phone'})) 
    email = forms.EmailField(label="", required=False, widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Enter your E-mail'})) 
    residence = forms.CharField(label="", max_length=50, required=False,  widget= forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Residence'})) 
    
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'phone', 'email','residence']


class Product_form(ModelForm):    
    class Meta:
        model = Product
        fields = "__all__"  
        exclude=['Business']
      
        
class Service_form(ModelForm):
    class Meta:
        model = Service
        fields = "__all__"
        exclude=['Business']
        

class ContactForm(ModelForm):
    first_name =forms.TextInput ()
    last_name = forms.TextInput()
    email = forms.TextInput()
    mobile = forms.TextInput()
    message = forms.TextInput()

    class Meta:
        model = Contact_us
        fields = '__all__' 
        
        
class SearchForm(forms.Form):
    search_term = forms.CharField()
    class Meta:
        fields = ["search_term"]

class ContactForm(ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    mobile = forms.CharField()
    message = forms.TextInput()

    class Meta:
        model = Contact_us
        fields = '__all__' 

    def __init__(self, *args, **kwargs):
        super(ContactForm,self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = "First Name"
        self.fields['last_name'].widget.attrs['placeholder'] = "Last Name"
        self.fields['email'].widget.attrs['placeholder'] = "Email"
        self.fields['mobile'].widget.attrs['placeholder'] = "Mobile"
        self.fields['message'].widget.attrs['placeholder'] = "Message"      
 
class OrderForm(forms.ModelForm):   
    class Meta:
        model = Order
        fields = ["address", 'phone', 'email']
        
        
class AppointmentForm(ModelForm):    
    date = forms.DateField(widget=DateTimeInput(attrs={'type': 'date'}))
    time = forms.TimeField(widget=DateTimeInput(attrs={'type': 'time'}))
    phone = forms.CharField(max_length=20)
    
    class Meta:
        model = Appointment
        fields = ['date', 'time', 'phone', "email"]         

ecommerce/business/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect,get_object_or_404

from django.contrib.auth.forms import UserCreationForm
from .forms import  *
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Product, Service, Category,Appointment,Review
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.db.models import Q
from django.contrib.auth.models import User, Group

from django.views.generic import ListView
from .forms import *
from formtools.wizard.views import SessionWizardView
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import os

from django.contrib.auth.decorators import login_required
from .decorators import *

from cart.forms import CartAddProductForm
from cart.cart import Cart

from .tasks import *



# Create your views here.

#Register the Business account
class CreateBusinessUser(SessionWizardView):
    form_list= [CreateUserForm, Business_Form]    
    template_name = 'register.html'
    file_storage = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'Images'))     

    def done(self, form_list, **kwargs):
        user_form = form_list[0]
        Business_form = form_list[1]
        if user_form.is_valid() and Business_form.is_valid():
            user = user_form.save()              
            Business_form.save(commit=False)
            Business_form.instance.user = user
            Business_form.save()
            group = Group.objects.get(name='Business')
            user.groups.add(group)
            return redirect ('business:login')
        else:
            return render(self.request, self.template_name, {'form_list': form_list})
    
#Register the Customer account
class CreateCustomerUser(SessionWizardView):
    form_list= [CreateUserForm, Customer_Form]    
    template_name = 'register.html'
    
    def done(self, form_list, **kwargs):
        user_form = form_list[0]
        Customer_form = form_list[1]
        if user_form.is_valid() and Customer_form.is_valid():
            user = user_form.save()            
            Customer_form.save(commit=False)
            Customer_form.instance.user = user
            Customer_form.save()
            group = Group.objects.get(name='Customer')
            user.groups.add(group)
            return redirect ('business:login')
        else:
            return render(self.request, self.template_name, {'form_list': form_list})
        
def loginPage(request):
    if request.method == "POST":
        Username = request.POST.get("username")
        Password = request.POST.get("password")
        user = authenticate(request, username=Username, password=Password)
        if user is not None:
            login(request, user)
            return redirect('business:home')
        else:
            messages.info(request, "username or password isn't correct")
    
    context = {}
    return render(request,"login.html", context )

def logoutUser(request):
    logout(request)
    return redirect('business:home')

def profile(request):
    return render(request, 'profile.html',{})


def update_info(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        form = UpdateInfoForm(request.POST or None, instance= current_user)
        if form.is_valid():
            form.save
            messages.success(request, "Your info has been updated")
            return redirect("business:home")
        return render(request, "update_info.html", {'form': form})

    else:
        messages.success(request, "You must be logged in first")
        return redirect("business:home")


def update_profile(request):
    if request.user.is_authenticated:
        current_user = User.objects.get(id=request.user.id)
        update_form = UpdateProfileForm(request.POST or None, instance= current_user)
        if update_form.is_valid():
            update_form.save
            login(request,current_user)
            messages.success(request, "Your profile has been updated")
            return redirect("business:home")
        

    else:
        messages.success(request, "You must be logged in first")
        return redirect("business:home")
    
    return render(request, "update_profile.html", {'update_form': update_form})
    
def update_password(request):
    if request.user.is_authenticated:
        current_user= request.user
        if request.method == "POST":
            form = UpdatePasswordForm(current_user,request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your password has been updated")
                return redirect('business:login')
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)
                    return redirect('business:update-password')
        else:
            form = UpdatePasswordForm(current_user)
            return render(request, "update_password.html", {'form': form})
    else:
        messages.success(request, "You must be logged in first")
        return redirect('business:home')
    
def category(request, foo):
    foo = foo.replace('-', ' ')

    try:
        category = Category.objects.get(name=foo)
        product = Product.objects.filter(category=category)
        return render(request, 'category.html', {'products': product, 'category': category})

    except Category.DoesNotExist:
         messages.success(request,"That category does not exist ... Please try again")
         return redirect('business:home')



@login_required
@business 
def add_product(request):
    submitted = False
    form = Product_form()
    
    if request.method == 'POST':
        form = Product_form(request.POST, request.FILES)
        if form.is_valid():
            #auto populates the form with the field business name
            user_id = request.user            
            business_id = Business.objects.get(user=user_id)             
            form.instance.Business = business_id            
            form.save()           
            return redirect('business:manage')
    else:
        form = Product_form()
        if 'submitted' in request.GET:
            submitted= True
    return render(request, 'add_product.html', {'form':form, 'submitted': submitted})

def product(request, pk ):
    product = get_object_or_404(Product, id=pk)
    cart_product_form = CartAddProductForm()

    if request.method =='POST':
       rating=request.POST.get('rating',3)
       content=request.POST.get('content','')
       if content:
            reviews=Review.objects.filter(created_by =request.user,product=product)
            if reviews.count()>0:
                review=reviews.first()
                review.rating=rating
                review.content=content
                review.save()

            else:
             review=Review.objects.create(
                product=product,
                rating=rating,
                content=content,
                created_by=request.user)

            
            return redirect('business:product',pk=pk)
    
    return render(request, 'product.html', {'product': product, 'cart_product_form':cart_product_form})

@login_required
@business 
def add_service(request):
    submitted = False
    form = Service_form()
   
    if request.method == 'POST':
        form = Service_form(request.POST, request.FILES)
        if form.is_valid():
            #auto populates the form with the field business name
            user_id = request.user            
            business_id = Business.objects.get(user=user_id)             
            form.instance.Business = business_id            
            form.save()           
            return redirect('business:manage')
    else:
        form = Service_form
        if 'submitted' in request.GET:
            submitted= True
    return render(request, 'add_service.html', {'form':form, 'submitted': submitted})

def service(request, pk):
    service = get_object_or_404(Service, id=pk)

    if request.method =='POST':
       rating=request.POST.get('rating',2)
       content=request.POST.get('content','')
       if content:
            reviews =Review.objects.filter(created_by =request.user, service=service)
            if review.count()>0:
                reviews=reviews.first()
                reviews.rating=rating
                reviews.content=content
                reviews.save()

            else:
                review = Review.objects.create(
                    service=service,
                    rating=rating,
                    content=content,
                    created_by=request.user)
             
            return redirect('business:service', pk=pk, permanent=True)

    return render(request, 'service.html', {'service': service})

    


def search(request):
    products = None  
    services = None 
   
    if request.method == "POST":
        searched_term = request.POST.get('search-term', '')  
       
        products = Product.objects.filter(product_name__icontains=searched_term)
        services = Service.objects.filter(service_name__icontains=searched_term)
    
        if not products and not services:
            messages.success(request, "That product or service does not exist ... Please try again")
        else:
            print(products)
            print(services)

    context = {
        "products": products,
        "services": services
    }
    return render(request, "search.html", context)

def service(request, pk):
    service = Service.objects.get(id=pk)
    return render(request, 'service.html', {'service': service})

def about(request):
    return render(request,"about.html",{})

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ContactForm()

ecommerce/business/templates/appointment.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">BOOK AN APPOINTMENT</h1>
      <form method="post">
        {% csrf_token %}
        
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary my-2">BOOK</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

ecommerce/business/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}            
<div id="carouselExampleIndicators" class="carousel slide  " data-ride="carousel" >
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active" style="height: 500px;">
        <img class="d-block w-100" src="{% static 'carousels\OnlineStore.png'%}"  alt="First slide" style="height: 100%; object-fit: cover;  filter:brightness(0.8)"   >
      </div>
      <div class="carousel-item"  style="height: 500px;" >
        <img class="d-block w-100" src="{% static 'carousels\Product.png'%}"  alt="Second slide" style="height: 100%; object-fit: cover; filter:brightness(0.6)" >
        <div class="carousel-caption d-none d-md-block">
            <h5>ORDER PRODUCTS ONLINE</h5>
            <p style="color: rgb(147, 15, 248); font-size:larger; font-weight: bolder;" >Get what you need, right when you need it.</p>
          </div>
      </div>
      <div class="carousel-item"  style="height: 500px;">
        <img class="d-block w-100" src="{% static 'carousels\Barbershop.png' %}" alt="Third slide" style="height: 100%; object-fit: cover; filter:brightness(0.6)" >
        <div class="carousel-caption d-none d-md-block">
            <h5>BOOK APPOINTMENTS ONLINE</h5>
            <p style="color: rgb(147, 15, 248); font-size:larger; font-weight: bolder;"  >Your time, your terms-book online!</p>
          </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>      
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>      
    </a>
</div>        
    <section class="py-6">
        <div id="outer" class="me-3 ms-3" >
            <div class="row  m-4" id="1" style="position:relative ;">
                <div style="display: flex; align-items: start; font-weight: bold; padding: 10px 20px;">
                    Discounted Products
                  </div>                          
                {% for product in discounted %}
                    {% if product.discount %}
                        <div class="col mb-3">
                            <div class="card">                        
                                <img class="card-img" src="{{ product.photo.url }}" alt="product image"  style="width: 100%; height: 180px; object-fit: contain;"  />                        
                                <div class="card-body p-1 bg-gradient">
                                    <div class="text-center">                               
                                        <h5 class="fw-bolder">{{product.product_name}}</h5>                                    
                                        <h3 class="text-primary " style="font-family: 'Times New Roman', Times, serif; color: rgb(18, 44, 128); text-decoration: line-through;"> Shs {{product.price}} </h3>  
                                        <h3 class="text-primary " style="font-family: 'Times New Roman', Times, serif; color: rgb(18, 44, 128);"> Shs {{product.discounted_price}} </h3>                                                         
                                        
                                    </div>
                                </div>                        
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-warning mt-auto btn-lg btn-block" href="{% url 'business:product' product.id %}">VIEW PRODUCT</a></div>                                
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <div  style="display: flex; align-items: flex-end; justify-content: flex-end;">                    
                    <a href="{% url 'business:product-list' %}" class="btn btn-sm btn-outline-warning">View More Products</a>                    
                </div>
            </div>

            <div class="row  m-4 mt-4" id="2" style="position:relative ;">
                <div style="display: flex; align-items: start; font-weight: bold; padding: 10px 20px;">
                    Products Available
                </div>                  
                {% for product in products %}
                    <div class="col mb-3">
                        <div class="card ">                        
                            <img class="card-img." src="{{ product.photo.url }}" alt="product image"  style="width: 100%; height: 180px; object-fit: contain;"  />                        
                            <div class="card-body p-1 bg-gradient">
                                <div class="text-center">                               
                                    <h5 class="fw-bolder">{{product.product_name}}</h5>                                    
                                    <h3 class="text-primary " style="font-family: 'Times New Roman', Times, serif; color: rgb(18, 44, 128);"> Shs {{product.price}} </h3>                                  
                                    
                                </div>
                            </div>                        
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-warning mt-auto btn-lg btn-block" href="{% url 'business:product' product.id %}">VIEW PRODUCT</a></div>                                
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div style="display: flex; align-items: flex-end; justify-content: flex-end;">                    
                    <a href="{% url 'business:product-list' %}" class="btn btn-sm btn-outline-warning">View More Products</a>                    
                </div>
            </div>
            
              
            <div class="row  m-4 mt-4" id="3">
                <div style="display: flex; align-items: start; font-weight: bold; padding: 10px 20px;">
                    Services Available
                </div>
                  
                {% for service in services %}
                    <div class="col mb-3" >
                        <div class="card">                        
                            <img class="card-img." src="{{ service.photo.url }}" alt="service image "  style="width: 100%; height: 180px; object-fit: cover;" />                        
                            <div class="card-body p-1">
                                <div class="text-center">                               
                                    <h5 class="fw-bolder " style="font-family: sans-serif;">{{service.service_name}} </h5>                             
                                    <h3 class="text-primary " style="font-family: 'Times New Roman', Times, serif; color: rgb(0, 255, 102);"> Shs {{service.price}} </h3>                                                       
                                    
                                </div>
                            </div>                      
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-warning mt-auto btn-lg btn-block" href="{% url 'business:service' service.id %}">VIEW SERVICE</a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div  style="display: flex; align-items: flex-end; justify-content: flex-end;">                    
                    <a href="{% url 'business:service-list' %}" class="btn btn-sm btn-outline-warning">View More Services</a>                    
                </div>
            </div>
        </div>
    </section>
   
{% endblock %}

ecommerce/business/templates/navbar.html
<style>
  .bg-red{
    background:#daa520;
  
  }
  .navbar-brand{    
    color:black;
    background:#daa520;
  }
  .navbar-nav .nav-item {
    margin-right: 15px;    
    padding: 3px;
  }
  .navbar-nav .nav-link {
    color: black !important;
  }
  .navbar-nav .nav-link:hover {
    color:orange !important;
  }
  .dropdown-menu {
    background-color: white;
    border: 1px solid rgba(0, 0, 0, 0.15);
  }
 
  .dropdown-menu a:hover {
    background-color: white !important;
    color:orange;
  }  

  .navbar {
    position: fixed; 
    top: 0;
    left: 0;
    width: 100%; 
    z-index: 100; 
  }

 
</style>
<nav class="navbar navbar-expand fixed-top bg-light" >
  <a href="{% url 'business:home' %}" class="navbar-brand ms-2 h1">OneSTOP</a>
  <button
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#navbarNav"
    class="navbar-toggler"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav  ml-auto ">
        <li class="nav-item active">
          <a href="{% url 'business:home' %}" class="nav-link active"> HOME </a>
        </li> 
                 
        {% if user.is_authenticated %}
            <div class="dropdown">
              <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                PROFILE
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <a href="{% url 'business:update-profile' %}" class="nav-link active"> UPDATE PROFILE</a>
                <a href="{% url 'business:update-info' %}" class="nav-link active"> UPDATE INFO</a>
              </div>
            </div>  
            <li>
              <a href="{% url 'business:logout'%}" class="nav-link active"> LOGOUT</a>
            </li>
            <li>
              <a href="{% url 'business:manage'%}" class="nav-link active"> MANAGE </a>
            </li>        
        {% else %}
            <li class="nav-item active">
              <a href="{% url 'business:login'%}" class="nav-link active"> LOGIN</a>
            </li>
            <div class="dropdown">
              <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                REGISTER
              </button>
              <ul class="dropdown-menu">                
                <li><a class="dropdown-item" href="{% url 'business:register_business'%}">Business Account</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'business:register_customer'%}">Customer Account</a></li>
              </ul>
            </div>
        {% endif %} 
        <div class="dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenu4" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            CATEGORY
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu4">
            <li></li><a href="{% url 'business:category' 'electronics' %}" class="nav-link "> Electronics</a></li>
            <li></li><a href="{% url 'business:category' 'fashion_beauty' %}" class="nav-link "> Fashion and Beauty</a></li>
            <li></li><a href="{% url 'business:category' 'sporting' %}" class="nav-link "> Sporting</a></li>
            <li></li><a href="{% url 'business:category' 'kids_corner' %}" class="nav-link "> Kids corner</a></li>
            <li></li><a href="{% url 'business:category' 'outdoor' %}" class="nav-link "> Outdoor</a></li>
            <li></li><a href="{% url 'business:category' 'home_living' %}" class="nav-link "> Home living</a></li>
            <li></li><a href="{% url 'business:category' 'groceries' %}" class="nav-link "> Groceries</a></li>            
          </div>
        </div>         
        
          
      </ul>
      <div class="container" style="display: flex; justify-content:space-between; align-items: center; margin-right: 0px;">
        <div class="container">
          <form method="POST" action="{% url 'business:search' %}" class="d-flex" role="search">
            {% csrf_token %} 
            <input class="form-control me-3" size="40" name="search-term" type="search" placeholder="Search Products, Services" aria-label="Search">
            <button class="btn btn-outline-warning me-3" type="submit">Search</button>
        </form>
        </div>
        <div id="my_cart" style="display: flex; align-items: center; border-radius: 5px; border-style: solid; padding: 5px;">
            <i class='bi-cart-fill me-1'></i> Cart
            <span class='badge bg-dark text-white ms-1 rounded-pill' id='cart_quantity'>{{ cart|length }}</span>
        </div>
        <script>          
          $('#my_cart').on('click', function() {              
              window.location.href = '{% url "cart:cart_detail" %}';
          });
        </script>
      </div>
    </div>
    
  </div>
</nav>

    
    